<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\twig;

use craft\elements\Asset;
use vitordiniz22\craftlens\helpers\AssetTitleHelper;
use vitordiniz22\craftlens\Plugin;
use vitordiniz22\craftlens\records\AssetAnalysisRecord;

/**
 * Twig global object exposing Lens helpers to templates as `lens.*`.
 */
class LensTwigGlobal
{
    public function getAnalysis(int $assetId): ?AssetAnalysisRecord
    {
        return Plugin::getInstance()->assetAnalysis->getAnalysis($assetId);
    }

    public function getTagsForAnalysis(int $analysisId): array
    {
        return Plugin::getInstance()->tagAggregation->getTagsForAnalysis($analysisId);
    }

    public function getColorsForAnalysis(int $analysisId): array
    {
        return Plugin::getInstance()->colorAggregation->getColorsForAnalysis($analysisId);
    }

    public function isAutoGeneratedTitle(Asset $asset): bool
    {
        return AssetTitleHelper::isAutoGenerated($asset);
    }

    public function getSetupStatus(): array
    {
        return Plugin::getInstance()->setupStatus->getSetupStatus();
    }

    public function getCriticalIssues(): array
    {
        return Plugin::getInstance()->setupStatus->getCriticalIssues();
    }

    public function hasCriticalIssues(): bool
    {
        return Plugin::getInstance()->setupStatus->hasCriticalIssues();
    }

    public function isFeatureAvailable(string $feature): bool
    {
        return Plugin::getInstance()->setupStatus->isFeatureAvailable($feature);
    }

    public function getFeatureRequirements(string $feature): array
    {
        return Plugin::getInstance()->setupStatus->getFeatureRequirements($feature);
    }

    public function getDuplicateCount(int $assetId): int
    {
        return Plugin::getInstance()->duplicateDetection->getUnresolvedDuplicateCountForAsset($assetId);
    }
}
