<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\twig;

use craft\elements\Asset;
use vitordiniz22\craftlens\enums\AnalysisStatus;
use vitordiniz22\craftlens\helpers\AssetTitleHelper;
use vitordiniz22\craftlens\Plugin;
use vitordiniz22\craftlens\records\AssetAnalysisRecord;

/**
 * Twig global object exposing Lens helpers to templates as `lens.*`.
 */
class LensTwigGlobal
{
    /**
     * Expose AnalysisStatus enum values for Twig templates.
     * Usage: `lens.status.pendingReview`, `lens.status.failed`, etc.
     *
     * @return array<string, string>
     */
    public function getStatus(): array
    {
        return [
            'pending' => AnalysisStatus::Pending->value,
            'processing' => AnalysisStatus::Processing->value,
            'completed' => AnalysisStatus::Completed->value,
            'failed' => AnalysisStatus::Failed->value,
            'pendingReview' => AnalysisStatus::PendingReview->value,
            'approved' => AnalysisStatus::Approved->value,
            'rejected' => AnalysisStatus::Rejected->value,
        ];
    }

    /**
     * Map of status values to translated labels.
     * Usage: `lens.statusLabels[statusValue]` or `lens.statusLabel(statusValue)`
     *
     * @return array<string, string>
     */
    public function getStatusLabels(): array
    {
        $labels = [];

        foreach (AnalysisStatus::cases() as $case) {
            $labels[$case->value] = $case->label();
        }

        return $labels;
    }

    /**
     * Get translated label for a single status value.
     * Usage: `lens.statusLabel('pending_review')` → 'Pending Review'
     */
    public function statusLabel(string $value): string
    {
        return AnalysisStatus::tryFrom($value)?->label() ?? $value;
    }

    public function getAnalysis(int $assetId): ?AssetAnalysisRecord
    {
        return Plugin::getInstance()->assetAnalysis->getAnalysis($assetId);
    }

    public function getTagsForAnalysis(int $analysisId): array
    {
        return Plugin::getInstance()->tagAggregation->getTagsForAnalysis($analysisId);
    }

    public function getColorsForAnalysis(int $analysisId): array
    {
        return Plugin::getInstance()->colorAggregation->getColorsForAnalysis($analysisId);
    }

    public function isAutoGeneratedTitle(Asset $asset): bool
    {
        return AssetTitleHelper::isAutoGenerated($asset);
    }

    public function getSetupStatus(): array
    {
        return Plugin::getInstance()->setupStatus->getSetupStatus();
    }

    public function getCriticalIssues(): array
    {
        return Plugin::getInstance()->setupStatus->getCriticalIssues();
    }

    public function hasCriticalIssues(): bool
    {
        return Plugin::getInstance()->setupStatus->hasCriticalIssues();
    }

    public function isFeatureAvailable(string $feature): bool
    {
        return Plugin::getInstance()->setupStatus->isFeatureAvailable($feature);
    }

    public function getFeatureRequirements(string $feature): array
    {
        return Plugin::getInstance()->setupStatus->getFeatureRequirements($feature);
    }

    public function getDuplicateCount(int $assetId): int
    {
        return Plugin::getInstance()->duplicateDetection->getUnresolvedDuplicateCountForAsset($assetId);
    }
}
