<?php

declare(strict_types=1);

namespace vitordiniz22\craftlenstests\unit\twig;

use Codeception\Test\Unit;
use craft\elements\Asset;
use vitordiniz22\craftlens\enums\AnalysisStatus;
use vitordiniz22\craftlens\twig\LensTwigGlobal;

/**
 * Unit tests for the pure methods on LensTwigGlobal.
 *
 * These exercise status/enum exposure and the AssetTitleHelper delegation —
 * no plugin services or DB access required.
 */
class LensTwigGlobalStatusTest extends Unit
{
    private LensTwigGlobal $global;

    protected function _before(): void
    {
        parent::_before();
        $this->global = new LensTwigGlobal();
    }

    // -- getStatus() --

    public function testGetStatusExposesAllEnumCasesWithShortKeys(): void
    {
        $status = $this->global->getStatus();

        $this->assertSame(AnalysisStatus::Pending->value, $status['pending']);
        $this->assertSame(AnalysisStatus::Processing->value, $status['processing']);
        $this->assertSame(AnalysisStatus::Completed->value, $status['completed']);
        $this->assertSame(AnalysisStatus::Failed->value, $status['failed']);
    }

    public function testGetStatusCoversEveryEnumCase(): void
    {
        $status = $this->global->getStatus();

        $this->assertCount(count(AnalysisStatus::cases()), $status);
    }

    // -- getStatusLabels() --

    public function testGetStatusLabelsKeyedByValueWithConcreteStrings(): void
    {
        // Pin the actual translated strings so a refactor that accidentally
        // swapped `$case->label()` for `$case->name` or `ucfirst($case->value)`
        // would fail. A self-referential `$case->label() === $case->label()`
        // check cannot catch that.
        $labels = $this->global->getStatusLabels();

        $this->assertSame('Pending', $labels['pending']);
        $this->assertSame('Processing', $labels['processing']);
        $this->assertSame('Analyzed', $labels['completed']);
        $this->assertSame('Failed', $labels['failed']);
        $this->assertCount(count(AnalysisStatus::cases()), $labels);
    }

    // -- statusLabel() --

    public function testStatusLabelReturnsTranslatedLabelForValidValue(): void
    {
        $this->assertSame(
            AnalysisStatus::Completed->label(),
            $this->global->statusLabel('completed')
        );
    }

    public function testStatusLabelFallsBackToInputWhenValueInvalid(): void
    {
        $this->assertSame('not_a_real_status', $this->global->statusLabel('not_a_real_status'));
    }

    public function testStatusLabelFallsBackOnEmptyString(): void
    {
        $this->assertSame('', $this->global->statusLabel(''));
    }

    // -- isAutoGeneratedTitle() --

    public function testIsAutoGeneratedTitleReturnsTrueForFilenameDerivedTitle(): void
    {
        $asset = new Asset();
        $asset->filename = 'sunset-beach.jpg';
        $asset->title = 'Sunset Beach';

        $this->assertTrue($this->global->isAutoGeneratedTitle($asset));
    }

    public function testIsAutoGeneratedTitleReturnsFalseForEditedTitle(): void
    {
        $asset = new Asset();
        $asset->filename = 'IMG_4472.jpg';
        $asset->title = 'Family holiday 2025';

        $this->assertFalse($this->global->isAutoGeneratedTitle($asset));
    }

    public function testIsAutoGeneratedTitleHandlesCraftDuplicateSuffix(): void
    {
        $asset = new Asset();
        $asset->filename = 'photo_2026-03-31-145230_abcd.jpg';
        $asset->title = 'Photo';

        $this->assertTrue($this->global->isAutoGeneratedTitle($asset));
    }

    public function testIsAutoGeneratedTitleReturnsTrueForEmptyTitle(): void
    {
        $asset = new Asset();
        $asset->filename = 'sunset-beach.jpg';
        $asset->title = '';

        $this->assertTrue($this->global->isAutoGeneratedTitle($asset));
    }
}
