<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\helpers;

use craft\elements\Asset;
use craft\helpers\Assets;

class AssetTitleHelper
{
    /**
     * Craft's duplicate-file suffix: `_YYYY-MM-DD-HHmmss_XXXX` with optional `_N` increment.
     *
     * @see \craft\services\Assets::getNameReplacementInFolder()
     */
    private const CRAFT_DUPLICATE_SUFFIX = '/_\d{4}-\d{2}-\d{2}-\d{6}_[a-zA-Z0-9]{4}(_\d{1,2})?$/';

    /**
     * Check whether the asset title is auto-generated from its filename
     * (i.e. the user has NOT manually edited it).
     *
     * Handles the case where Craft resolves a filename conflict by appending a
     * timestamp suffix (e.g. `photo_2026-03-31-145230_abcd.jpg`). The title is
     * derived from the original name before the rename, so we strip the suffix
     * and re-check when the direct comparison fails.
     */
    public static function isAutoGenerated(Asset $asset): bool
    {
        $title = $asset->title ?? '';

        if ($title === '') {
            return true;
        }

        $stem = pathinfo($asset->filename, PATHINFO_FILENAME);

        return self::titleMatchesStem($title, $stem)
            || self::titleMatchesStem($title, self::stripDuplicateSuffix($stem));
    }

    /**
     * Remove Craft's conflict-resolution suffix from a filename stem.
     * Returns the stem unchanged when no suffix is present.
     */
    private static function stripDuplicateSuffix(string $stem): string
    {
        return preg_replace(self::CRAFT_DUPLICATE_SUFFIX, '', $stem);
    }

    private static function titleMatchesStem(string $title, string $stem): bool
    {
        return strcasecmp($title, Assets::filename2Title($stem)) === 0
            || strcasecmp($title, $stem) === 0;
    }
}
