<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\helpers;

use craft\elements\Asset;
use craft\helpers\Assets;

class AssetTitleHelper
{
    public static function isAutoGenerated(Asset $asset): bool
    {
        $currentTitle = $asset->title ?? '';

        if ($currentTitle === '') {
            return true;
        }

        $filename = pathinfo($asset->filename, PATHINFO_FILENAME);
        $craftGenerated = Assets::filename2Title($filename);

        return strcasecmp($currentTitle, $craftGenerated) === 0
            || strcasecmp($currentTitle, $filename) === 0;
    }
}
