<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\helpers;

use craft\elements\Asset;

class AssetTitleHelper
{
    public static function isAutoGenerated(Asset $asset): bool
    {
        $currentTitle = $asset->title ?? '';

        if ($currentTitle === '') {
            return true;
        }

        $filename = pathinfo($asset->filename, PATHINFO_FILENAME);
        $normalizedFromFilename = self::normalizeFilename($filename);

        $titlesMatch = strcasecmp($currentTitle, $normalizedFromFilename) === 0;
        $matchesRawFilename = strcasecmp($currentTitle, $filename) === 0;

        return $titlesMatch || $matchesRawFilename;
    }

    private static function normalizeFilename(string $filename): string
    {
        $withSpaces = str_replace(['-', '_'], ' ', $filename);

        return ucwords(strtolower($withSpaces));
    }
}
