<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\fieldlayoutelements;

use Craft;
use craft\base\ElementInterface;
use craft\elements\Asset;
use craft\fieldlayoutelements\BaseUiElement;
use vitordiniz22\craftlens\enums\LogCategory;
use vitordiniz22\craftlens\helpers\AssetTitleHelper;
use vitordiniz22\craftlens\helpers\Logger;
use vitordiniz22\craftlens\Plugin;
use vitordiniz22\craftlens\web\assets\lens\LensAssetActionsAsset;

class LensAnalysisElement extends BaseUiElement
{
    public static function displayName(): string
    {
        return Craft::t('lens', 'AI Analysis Panel');
    }

    public static function icon(): ?string
    {
        return 'wand-magic-sparkles';
    }

    protected function selectorIcon(): ?string
    {
        return 'wand-magic-sparkles';
    }

    public function isMultiInstance(): bool
    {
        return false;
    }

    protected function selectorLabel(): string
    {
        return Craft::t('lens', 'AI Analysis');
    }

    public function formHtml(?ElementInterface $element = null, bool $static = false): ?string
    {
        if (!$element instanceof Asset) {
            return null;
        }

        if ($element->kind !== Asset::KIND_IMAGE) {
            return null;
        }

        $currentUser = Craft::$app->getUser()->getIdentity();

        if ($currentUser === null || !$currentUser->can('accessPlugin-lens')) {
            return null;
        }

        try {
            Craft::$app->getView()->registerAssetBundle(LensAssetActionsAsset::class);

            $plugin = Plugin::getInstance();
            $analysis = $plugin->assetAnalysis->getAnalysis($element->id);
            $settings = $plugin->getSettings();
            $tags = [];
            $colors = [];
            $exifData = null;
            $similarImages = [];

            if ($analysis) {
                $tags = $plugin->tagAggregation->getTagsForAnalysis($analysis->id);
                $colors = $plugin->colorAggregation->getColorsForAnalysis($analysis->id);

                if ($analysis->hasExifMetadata) {
                    $exifData = $analysis->exifMetadata;
                }

                $similarImages = $plugin->duplicateDetection->getSimilarAssetsForDisplay($element->id);
            }

            return Craft::$app->view->renderTemplate(
                'lens/_components/analysis-panel.twig',
                [
                    'asset' => $element,
                    'analysis' => $analysis,
                    'settings' => $settings,
                    'isAutoGeneratedTitle' => AssetTitleHelper::isAutoGenerated($element),
                    'static' => $static,
                    'analysisTags' => $tags,
                    'analysisColors' => $colors,
                    'exifData' => $exifData,
                    'similarImages' => $similarImages,
                ]
            );
        } catch (\Throwable $e) {
            Logger::error(LogCategory::AssetProcessing, "Analysis panel render error: {$e->getMessage()}", $element->id, $e);
            return '<div class="lens-analysis-panel"><p class="error">'
                . Craft::t('lens', 'Unable to load analysis panel.')
                . '</p></div>';
        }
    }
}
