<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\fieldlayoutelements;

use Craft;
use craft\base\ElementInterface;
use craft\elements\Asset;
use craft\fieldlayoutelements\BaseUiElement;
use vitordiniz22\craftlens\enums\LogCategory;
use vitordiniz22\craftlens\helpers\AssetTitleHelper;
use vitordiniz22\craftlens\helpers\FieldLayoutHelper;
use vitordiniz22\craftlens\helpers\ImageQualityChecker;
use vitordiniz22\craftlens\helpers\Logger;
use vitordiniz22\craftlens\helpers\MultisiteHelper;
use vitordiniz22\craftlens\helpers\ImageMetricsAnalyzer;
use vitordiniz22\craftlens\Plugin;
use vitordiniz22\craftlens\web\assets\lens\LensAssetActionsAsset;

class LensAnalysisElement extends BaseUiElement
{
    public static function displayName(): string
    {
        return Craft::t('lens', 'Lens Analysis');
    }

    public static function icon(): ?string
    {
        return 'wand-magic-sparkles';
    }

    protected function selectorIcon(): ?string
    {
        return 'wand-magic-sparkles';
    }

    public function isMultiInstance(): bool
    {
        return false;
    }

    protected function selectorLabel(): string
    {
        return Craft::t('lens', 'Lens Analysis');
    }

    public function formHtml(?ElementInterface $element = null, bool $static = false): ?string
    {
        if (!$element instanceof Asset) {
            return null;
        }

        if ($element->kind !== Asset::KIND_IMAGE) {
            return null;
        }

        $currentUser = Craft::$app->getUser()->getIdentity();

        if ($currentUser === null || !$currentUser->can('accessPlugin-lens')) {
            return null;
        }

        try {
            Craft::$app->getView()->registerAssetBundle(LensAssetActionsAsset::class);

            $plugin = Plugin::getInstance();
            $settings = $plugin->getSettings();

            if (!$settings->isVolumeEnabled($element->getVolume()->id)) {
                return Craft::$app->view->renderTemplate(
                    'lens/_components/analysis-panel-volume-disabled.twig',
                    ['asset' => $element],
                );
            }

            $analysis = $plugin->assetAnalysis->getAnalysis($element->id);
            $tags = [];
            $colors = [];
            $similarImages = [];
            $totalSimilarCount = 0;
            $siteContent = [];

            if ($analysis) {
                $tags = $plugin->tagAggregation->getTagsForAnalysis($analysis->id);
                $colors = $plugin->colorAggregation->getColorsForAnalysis($analysis->id);

                if ($plugin->getIsPro()) {
                    $similarImages = $plugin->duplicateDetection->getSimilarAssetsForDisplay($element->id);
                    $totalSimilarCount = $plugin->duplicateDetection->getUnresolvedDuplicateCountForAsset($element->id);
                }

                if (MultisiteHelper::needsMultisiteContent($element)) {
                    $siteRecords = $plugin->siteContent->getAllSiteContent($analysis->id);
                    $sitesNeeded = MultisiteHelper::getSitesNeedingContent($element);
                    $allSites = Craft::$app->getSites()->getAllSites();
                    $siteNames = [];

                    foreach ($allSites as $site) {
                        $siteNames[$site->id] = $site->name;
                    }

                    // Show ALL sites that need content, merging existing records
                    foreach ($sitesNeeded as $siteInfo) {
                        $siteId = $siteInfo['siteId'];
                        $record = $siteRecords[$siteId] ?? null;

                        $siteContent[] = [
                            'siteId' => $siteId,
                            'language' => $record?->language ?? $siteInfo['language'],
                            'siteName' => $siteNames[$siteId] ?? "Site {$siteId}",
                            'altText' => $record?->altText ?? null,
                            'altTextAi' => $record?->altTextAi ?? null,
                            'altTextConfidence' => $record?->altTextConfidence ?? null,
                            'suggestedTitle' => $record?->suggestedTitle ?? null,
                            'suggestedTitleAi' => $record?->suggestedTitleAi ?? null,
                            'titleConfidence' => $record?->titleConfidence ?? null,
                        ];
                    }
                }
            }

            return Craft::$app->view->renderTemplate(
                'lens/_components/analysis-panel.twig',
                [
                    'asset' => $element,
                    'analysis' => $analysis,
                    'settings' => $settings,
                    'isAutoGeneratedTitle' => AssetTitleHelper::isAutoGenerated($element),
                    'assetAlt' => $element->alt ?? '',
                    'isAltEmpty' => empty($element->alt),
                    'altFieldInLayout' => FieldLayoutHelper::hasAltField($element),
                    'static' => $static,
                    'analysisTags' => $tags,
                    'analysisColors' => $colors,
                    'similarImages' => $similarImages,
                    'totalSimilarCount' => $totalSimilarCount,
                    'siteContent' => $siteContent,
                    'isAltTranslatable' => MultisiteHelper::isAltTranslatable($element->getVolume()->id),
                    'isTitleTranslatable' => MultisiteHelper::isTitleTranslatable($element->getVolume()->id),
                    'currentSiteId' => $element->siteId,
                    'primarySiteId' => Craft::$app->getSites()->getPrimarySite()->id,
                    'webReadiness' => ImageQualityChecker::assess($element),
                    'qualityMetrics' => $analysis ? ImageMetricsAnalyzer::assessFromRecord(
                        $analysis->sharpnessScore !== null ? (float) $analysis->sharpnessScore : null,
                        $analysis->exposureScore !== null ? (float) $analysis->exposureScore : null,
                        $analysis->noiseScore !== null ? (float) $analysis->noiseScore : null,
                        $analysis->compressionQuality !== null ? (int) $analysis->compressionQuality : null,
                        $analysis->colorProfile,
                        $analysis->shadowClipRatio !== null ? (float) $analysis->shadowClipRatio : null,
                        $analysis->highlightClipRatio !== null ? (float) $analysis->highlightClipRatio : null,
                    ) : [],
                ]
            );
        } catch (\Throwable $e) {
            Logger::error(LogCategory::AssetProcessing, "Analysis panel render error: {$e->getMessage()}", $element->id, $e);
            return '<div class="lens-analysis-panel"><p class="error">'
                . Craft::t('lens', 'Unable to load analysis panel.')
                . '</p></div>';
        }
    }
}
