<?php

declare(strict_types=1);

namespace vitordiniz22\craftlens\fieldlayoutelements;

use Craft;
use craft\base\ElementInterface;
use craft\elements\Asset;
use craft\fieldlayoutelements\BaseUiElement;
use vitordiniz22\craftlens\enums\LogCategory;
use vitordiniz22\craftlens\helpers\AssetTitleHelper;
use vitordiniz22\craftlens\helpers\Logger;
use vitordiniz22\craftlens\helpers\MultisiteHelper;
use vitordiniz22\craftlens\Plugin;
use vitordiniz22\craftlens\web\assets\lens\LensAssetActionsAsset;

class LensAnalysisElement extends BaseUiElement
{
    public static function displayName(): string
    {
        return Craft::t('lens', 'Lens Analysis');
    }

    public static function icon(): ?string
    {
        return 'wand-magic-sparkles';
    }

    protected function selectorIcon(): ?string
    {
        return 'wand-magic-sparkles';
    }

    public function isMultiInstance(): bool
    {
        return false;
    }

    protected function selectorLabel(): string
    {
        return Craft::t('lens', 'Lens Analysis');
    }

    public function formHtml(?ElementInterface $element = null, bool $static = false): ?string
    {
        if (!$element instanceof Asset) {
            return null;
        }

        if ($element->kind !== Asset::KIND_IMAGE) {
            return null;
        }

        $currentUser = Craft::$app->getUser()->getIdentity();

        if ($currentUser === null || !$currentUser->can('accessPlugin-lens')) {
            return null;
        }

        try {
            Craft::$app->getView()->registerAssetBundle(LensAssetActionsAsset::class);

            $plugin = Plugin::getInstance();
            $analysis = $plugin->assetAnalysis->getAnalysis($element->id);
            $settings = $plugin->getSettings();
            $tags = [];
            $colors = [];
            $exifData = null;
            $similarImages = [];
            $siteContent = [];

            if ($analysis) {
                $tags = $plugin->tagAggregation->getTagsForAnalysis($analysis->id);
                $colors = $plugin->colorAggregation->getColorsForAnalysis($analysis->id);

                if ($analysis->hasExifMetadata) {
                    $exifData = $analysis->exifMetadata;
                }

                $similarImages = $plugin->duplicateDetection->getSimilarAssetsForDisplay($element->id);

                if (MultisiteHelper::needsMultisiteContent($element)) {
                    $siteRecords = $plugin->siteContent->getAllSiteContent($analysis->id);
                    $allSites = Craft::$app->getSites()->getAllSites();
                    $siteNames = [];

                    foreach ($allSites as $site) {
                        $siteNames[$site->id] = $site->name;
                    }

                    foreach ($siteRecords as $siteId => $record) {
                        $siteContent[] = [
                            'siteId' => $siteId,
                            'language' => $record->language,
                            'siteName' => $siteNames[$siteId] ?? "Site {$siteId}",
                            'altText' => $record->altText,
                            'altTextAi' => $record->altTextAi,
                            'altTextConfidence' => $record->altTextConfidence,
                            'altTextEditedBy' => $record->altTextEditedBy,
                            'suggestedTitle' => $record->suggestedTitle,
                            'suggestedTitleAi' => $record->suggestedTitleAi,
                            'titleConfidence' => $record->titleConfidence,
                            'suggestedTitleEditedBy' => $record->suggestedTitleEditedBy,
                        ];
                    }
                }
            }

            return Craft::$app->view->renderTemplate(
                'lens/_components/analysis-panel.twig',
                [
                    'asset' => $element,
                    'analysis' => $analysis,
                    'settings' => $settings,
                    'isAutoGeneratedTitle' => AssetTitleHelper::isAutoGenerated($element),
                    'assetAlt' => $element->alt ?? '',
                    'isAltEmpty' => empty($element->alt),
                    'altFieldInLayout' => Plugin::getInstance()->hasAltFieldInLayout($element),
                    'static' => $static,
                    'analysisTags' => $tags,
                    'analysisColors' => $colors,
                    'exifData' => $exifData,
                    'similarImages' => $similarImages,
                    'siteContent' => $siteContent,
                    'isAltTranslatable' => MultisiteHelper::isAltTranslatable($element->getVolume()->id),
                    'isTitleTranslatable' => MultisiteHelper::isTitleTranslatable($element->getVolume()->id),
                ]
            );
        } catch (\Throwable $e) {
            Logger::error(LogCategory::AssetProcessing, "Analysis panel render error: {$e->getMessage()}", $element->id, $e);
            return '<div class="lens-analysis-panel"><p class="error">'
                . Craft::t('lens', 'Unable to load analysis panel.')
                . '</p></div>';
        }
    }
}
